### ISSUE TITLE
getFileBody in serverdide

### ISSUE THREAD

**Issue by mohamadrezash** [amitshekhariitbhu/Fast-Android-Networking#160]
hi.
how i get posted file with addFileBody(file) that in post method on server using php?

**Comment by amitshekhariitbhu** [comment]
Check this [link](https://www.w3schools.com/php/php_file_upload.asp).

**Comment by mohamadrezash** [comment]
what is the key of posted file?
my point is whe get the file in php wihe `$_FILES["key"]["value"]`  .
now i dont know what is the key in addFileBody(file).

**Comment by mohamadrezash** [comment]
in `AndroidNetworking.upload(url).addMultipartFile("image",file)` the key of posted file is image but in 
`AndroidNetworking.post("https://fierce-cove-29863.herokuapp.com/postFile") .addFileBody(file)` i dont know what is the key

**Comment by mohamadrezash** [comment]
any idea dear?

**Comment by johnwatsondev** [comment]
@mohamadrezash It should just get HttpBody as InputStream from HttpRequest on the server side. 

Because of the RequestBody is just a inputStream of your file.

```
// ANRequest.java's getRequestBody() method
RequestBody.create(customMediaType, mFile);
```

[Here](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/PostFile.java) is the okhttp3's sample of post file.
