### ISSUE TITLE
Android Networking library

### ISSUE THREAD

**Issue by vnaeimabadi** [amitshekhariitbhu/Fast-Android-Networking#5]
hi,
thanks for your library.
I have a question about posting data:
when i send persion character to server with your library.in server the charaters are not same.
for example i send "ولی" to server. in server it show "#as$*^".
how can i send UTF-8 ?

**Comment by amitshekhariitbhu** [comment]
@vnaeimabadi : can you tell us the problem in more detail. You can send us the request that you are making(sample code snippet), so that we can figure out the problem. Any way we have tested that it send data using UTF-8. There may be the problem from server side as we have to enable it in database column by making collation -> utf8_general_ci, so that it supports different language.Where are you seeing this character in database or printing ?
