### ISSUE TITLE
Parse / Serialize json string datetime to java.util.Date

### ISSUE THREAD

**Issue by nurhadi-ab** [amitshekhariitbhu/Fast-Android-Networking#88]
Hi,
I have a question about DateTime Parser.
How to parse json string with datetime formatted into java.util.Date?

Here is my json:
```
{
    "title": "Integer ante arcu accumsan a.",
    "date_post": "2016-04-06T16:00:05"
}
```

And this is my java:
```
public class PostModel {
    private String title;
    private Date datePost;

    public PostModel(String title, Date datePost) {
        this.title = title;
        this.datePost = datePost;
    }

    // ...

    public Date getDatePost() {
        return datePost;
    }
}
```

I use in a request using `getAsParsed ` method.
When I apply the data to the view, the getDatePost() returning null value.

thanks.
*) sorry for my english

**Comment by amitshekhariitbhu** [comment]
First of all, please update the library to latest version and use `getAsObject` or `getAsObjectList` instead of `getAsParsed`.
There are two ways:
First:
Convert your datePost into `String` type in the model class.
```
SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); // your format
Date date = format.parse(datePost);
```
Second:
You can customize GSON Parser according to your date format and pass it to the Fast-Android-Networking after initializing it as below:
```
Gson gson = new GsonBuilder().setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'").create(); // your format
AndroidNetworking.setParserFactory(new GsonParserFactory(gson));
```

**Comment by nurhadi-ab** [comment]
Thank you @amitshekhariitbhu for the quick reply.
and thank you, this is works. I like the second way because its only once for the global and I don't want any changes in my model.
